#!/usr/bin/env python3
"""Inject `modulepreload` hints for the DBX startup module graph into index.html.

Why this exists
---------------
The DBX web bundle is heavily code-split: the startup graph (entry chunk plus
the `i18n` / `App.vue` dynamic imports and their static closures) is ~243 chunks
/ ~4.5 MB, but the generated `index.html` only preloads four chunks. Every other
chunk is discovered by the parser one import level at a time, so the first paint
pays for that discovery waterfall on a cold HTTP cache.

This script rewrites the *built* `index.html` in place, adding a generated block
of `<link rel="modulepreload">` tags for the startup chunks above a size
threshold (the big chunks are ~90% of the bytes, so a couple of dozen tags cover
almost all of the payload). The block is idempotent: re-running replaces the
previous generated block instead of appending to it.

Re-run it after every `rawfile/dbx-dist` replacement (see AGENTS.md,
"HAP 产物重建"). It only touches `index.html`; chunk files are never modified.

Usage:
    python3 harmony/tools/inject_modulepreload.py [dist_dir] [--threshold BYTES]
"""

from __future__ import annotations

import argparse
import os
import re
import sys

BEGIN_MARKER = "<!-- dbx-startup-modulepreload:begin -->"
END_MARKER = "<!-- dbx-startup-modulepreload:end -->"
DEFAULT_THRESHOLD = 16 * 1024

# Static ESM references as emitted by rolldown/vite:
#   `... from"./chunk.js"` for imports/exports, `import"./chunk.js"` for
#   side-effect imports. Dynamic `import("./chunk.js")` is deliberately not
#   followed: those chunks are lazy by definition.
_FROM_RE = re.compile(r'from\s*"\./([^"]+?\.js)"')
_SIDE_EFFECT_RE = re.compile(r'(?<![\w.])import\s*"\./([^"]+?\.js)"')
_ENTRY_RE = re.compile(r'<script[^>]*\btype="module"[^>]*\bsrc="\./([^"]+?\.js)"[^>]*>')
_PRELOAD_RE = re.compile(r'<link[^>]*\brel="modulepreload"[^>]*\bhref="\./([^"]+?\.js)"')
_ASSET_HREF_RE = re.compile(r'\bhref="\./([^"]+?\.js)"')


def read_text(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def strip_generated_block(html: str) -> str:
    begin = html.find(BEGIN_MARKER)
    end = html.find(END_MARKER)
    if begin == -1 or end == -1 or end < begin:
        return html
    end += len(END_MARKER)
    # Also swallow the newline that followed the block, if any.
    while end < len(html) and html[end] in "\r\n":
        end += 1
    return html[:begin] + html[end:]


def module_paths(dist_dir: str, rel_path: str) -> list[str]:
    """Static imports of one chunk, resolved to dist-relative paths."""
    source = read_text(os.path.join(dist_dir, rel_path))
    refs = set(_FROM_RE.findall(source)) | set(_SIDE_EFFECT_RE.findall(source))
    base = os.path.dirname(rel_path)
    resolved = []
    for ref in refs:
        candidate = os.path.normpath(os.path.join(base, ref)).replace(os.sep, "/")
        resolved.append(candidate)
    return resolved


def collect_closure(dist_dir: str, roots: list[str]) -> dict[str, int]:
    """Size of every chunk reachable from `roots` through static imports."""
    sizes: dict[str, int] = {}
    pending = list(roots)
    while pending:
        rel = pending.pop()
        if rel in sizes:
            continue
        path = os.path.join(dist_dir, rel)
        if not os.path.isfile(path):
            continue
        sizes[rel] = os.path.getsize(path)
        pending.extend(module_paths(dist_dir, rel))
    return sizes


def build_block(chunks: list[tuple[str, int]]) -> str:
    lines = [BEGIN_MARKER, "    <!-- generated by harmony/tools/inject_modulepreload.py; do not edit by hand -->"]
    for rel, size in chunks:
        lines.append(f'    <link rel="modulepreload" crossorigin href="./{rel}" />')
    lines.append(f"    {END_MARKER}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "dist_dir",
        nargs="?",
        default=os.path.join("harmony", "dbxohos", "entry", "src", "main", "resources", "rawfile", "dbx-dist"),
        help="directory holding the built frontend (default: the HAP rawfile dist)",
    )
    parser.add_argument("--threshold", type=int, default=DEFAULT_THRESHOLD, help="minimum chunk size in bytes")
    args = parser.parse_args()

    index_path = os.path.join(args.dist_dir, "index.html")
    if not os.path.isfile(index_path):
        print(f"error: {index_path} not found", file=sys.stderr)
        return 1

    html = strip_generated_block(read_text(index_path))
    entry_match = _ENTRY_RE.search(html)
    if not entry_match:
        print("error: no module entry script found in index.html", file=sys.stderr)
        return 1
    entry = entry_match.group(1)

    already = set(_PRELOAD_RE.findall(html))
    # Keep pre-existing hints as roots (they are startup chunks too) and as
    # exclusions (never emit a duplicate tag).
    roots = [entry] + sorted(already)
    assets_dir = os.path.join(args.dist_dir, "assets")
    if os.path.isdir(assets_dir):
        # The two dynamic imports `main.ts` awaits before mounting the app.
        for name in sorted(os.listdir(assets_dir)):
            if name.endswith(".js") and (name.startswith("i18n-") or name.startswith("App-")) and name != entry:
                candidate = f"assets/{name}"
                if candidate not in roots:
                    roots.append(candidate)

    closure = collect_closure(args.dist_dir, roots)
    # Never hint the entry itself (it is already the module script) nor a chunk
    # that index.html already hints.
    excluded = set(already) | {entry}
    selected = sorted(
        ((rel, size) for rel, size in closure.items() if rel not in excluded and size >= args.threshold),
        key=lambda item: (-item[1], item[0]),
    )

    block = build_block(selected)
    # Insert directly before the entry module script, matching what the bundler
    # emits for its own hints. (`<script src>` ignores inline content, so the
    # block must never land between the opening and closing tags.)
    insert_at = entry_match.start()
    html = html[:insert_at] + block + "\n" + html[insert_at:]
    with open(index_path, "w", encoding="utf-8") as handle:
        handle.write(html)

    total = sum(size for _, size in selected)
    print(
        f"{index_path}: entry={entry} closure={len(closure)} chunks "
        f"({sum(closure.values()) / 1048576:.2f} MB), injected {len(selected)} hints "
        f"({total / 1048576:.2f} MB, threshold {args.threshold}B)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
